# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - gigwork-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_bd117c2abf9049809f7764c614b233d3 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_13dca2c230fd47bc8ffbc2150bd76df3 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bd117c2abf9049809f7764c614b233d3 }}/gigwork_server:${{ github.sha }}
          file: ./Dockerfile
          build-args: |
            cloudinaryCloudName=${{secrets.CLOUDINARYCLOUDNAME}}
            cloudinaryApiKey=${{secrets.CLOUDINARYAPIKEY}}
            cloudinaryApiSecret=${{secrets.CLOUDINARYAPISECRET}}
            secretKey=${{secrets.SECRETKEY}}
            DockerDBID=${{secrets.DOCKERDBID}}
            redisPassword=${{secrets.REDISPASSWORD}}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "gigwork-server"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1df74d55db3948419fa0221382b73fc1 }}
          images: "index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bd117c2abf9049809f7764c614b233d3 }}/gigwork_server:${{ github.sha }}"
